#!/usr/bin/env python3
"""
LUMI Cyclic DLP Trainer — Standalone script for training large DLP solvers on LUMI-G.

10x model size (~35M params), 20x dataset (150k train), 10x problem size (p=10007, 14-bit)
compared to local MPS experiments (3.3M params, 7.5k train, p=251, 8-bit).

Covers all cyclic DLP types:
  - L6:  Finite field DLP   (g^x = h mod p,  cyclic subgroup of F_p^*)
  - L7:  Elliptic curve DLP ([a]G = Q on E/F_p,  cyclic subgroup of E(F_p))
  - MDLP: Matrix group DLP  (M^a = N in GL(2,F_p),  cyclic subgroup generated by M)
  - PDLP: Permutation DLP   (sigma^a = tau in S_n,  cyclic subgroup generated by sigma)

Features:
  - Progressive weight decay (0.05 -> 0.30, ramped as train accuracy improves)
  - Learning curve tracking (metrics.jsonl, checkpoints, phase detection)
  - Mixed precision (AMP) for GPU speed
  - Multi-GPU via DDP (optional, for multi-GCD LUMI nodes)
  - WandB logging (optional)

No external dependencies beyond PyTorch + NumPy. Completely standalone.

Usage (single GPU):
    python lumi_cyclic_dlp_trainer.py --problem L6 --prime 10007 \\
        --d-model 512 --n-layers 8 --n-heads 16 \\
        --epochs 200000 --train-size 150000 \\
        --wd-start 0.05 --wd-max 0.30 --wd-step 0.05 --wd-acc-threshold 0.05 \\
        --output-dir results/lumi/L6_p10007

Usage (multi-GPU via torchrun):
    torchrun --standalone --nproc_per_node=4 lumi_cyclic_dlp_trainer.py \\
        --problem L6 --prime 10007 --d-model 512 --n-layers 8 --n-heads 16 \\
        --epochs 200000 --train-size 150000 --output-dir results/lumi/L6_p10007

Usage (generate dataset only):
    python lumi_cyclic_dlp_trainer.py --problem L6 --prime 10007 \\
        --train-size 150000 --generate-only --output-dir data/lumi
"""
from __future__ import annotations

import argparse
import json
import math
import os
import random
import sys
import time
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# ============================================================================
# Problem Generators — All Cyclic DLP Types
# ============================================================================

@dataclass
class ProblemSpec:
    """Specification of a single problem instance."""
    problem_id: str
    prime: int
    inputs: List[int]
    target: int
    metadata: Dict


class ProblemGenerator:
    """Base class for problem generators."""
    problem_id: str = "base"
    n_inputs: int = 1

    def __init__(self, p: int, seed: int = 42):
        self.p = p
        self.seed = seed
        self.rng = random.Random(seed)

    def generate_all(self) -> List[ProblemSpec]:
        raise NotImplementedError

    def generate(self, n: int) -> List[ProblemSpec]:
        all_specs = self.generate_all()
        if n >= len(all_specs):
            return all_specs
        return self.rng.sample(all_specs, n)

    def solution_space_size(self) -> int:
        raise NotImplementedError

    def verify(self, spec: ProblemSpec) -> bool:
        raise NotImplementedError


def _prime_factors(n: int) -> List[int]:
    factors = []
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors.append(d)
            n //= d
        d += 1
    if n > 1:
        factors.append(n)
    return factors


def _primitive_roots(p: int) -> List[int]:
    """Find all primitive roots modulo p."""
    if p == 2:
        return [1]
    roots = []
    factors = set(_prime_factors(p - 1))
    for g in range(2, p):
        if all(pow(g, (p - 1) // q, p) != 1 for q in factors):
            roots.append(g)
    return roots


def _is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0:
        return False
    d = n - 1
    r = 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for a in [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]:
        if a >= n:
            continue
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True


# ---------------------------------------------------------------------------
# L6: Finite Field Discrete Logarithm — g^x = h mod p
# ---------------------------------------------------------------------------

class FiniteFieldDLPGenerator(ProblemGenerator):
    """L6: Given (g, h), find x: g^x = h mod p.

    Uses primitive roots as generators. The cyclic group is Z_{p-1}
    (the multiplicative group F_p^* is cyclic of order p-1).
    """
    problem_id = "L6"
    n_inputs = 2

    def __init__(self, p: int, seed: int = 42):
        super().__init__(p, seed)
        self._cached_roots = None

    def _get_roots(self):
        if self._cached_roots is None:
            self._cached_roots = _primitive_roots(self.p)
        return self._cached_roots

    def generate(self, n: int) -> List[ProblemSpec]:
        roots = self._get_roots()
        specs = []
        seen = set()
        max_attempts = n * 10
        attempts = 0
        while len(specs) < n and attempts < max_attempts:
            g = self.rng.choice(roots)
            x = self.rng.randint(1, self.p - 1)
            h = pow(g, x, self.p)
            key = (g, h)
            if key not in seen:
                seen.add(key)
                specs.append(ProblemSpec(
                    problem_id=self.problem_id,
                    prime=self.p,
                    inputs=[g, h],
                    target=x,
                    metadata={"g": g, "h": h, "x": x},
                ))
            attempts += 1
        return specs

    def generate_all(self) -> List[ProblemSpec]:
        return self.generate(min(self.solution_space_size(), 500000))

    def solution_space_size(self) -> int:
        roots = self._get_roots()
        return (self.p - 1) * len(roots)

    def verify(self, spec: ProblemSpec) -> bool:
        g, h, x = spec.metadata["g"], spec.metadata["h"], spec.target
        return pow(g, x, self.p) == h


# ---------------------------------------------------------------------------
# L7: Elliptic Curve Discrete Logarithm — [a]G = Q on E/F_p
# ---------------------------------------------------------------------------

class EllipticCurveDLPGenerator(ProblemGenerator):
    """L7: Given (Gx, Gy, Qx, Qy), find a: [a]G = Q on a fixed curve.

    Uses y^2 = x^3 + A*x + B mod p. The cyclic group is the subgroup
    of E(F_p) generated by G.
    """
    problem_id = "L7"
    n_inputs = 4
    _A = 3
    _B = 7

    def __init__(self, p: int, seed: int = 42):
        super().__init__(p, seed)
        self._cached_gen = None
        self._cached_order = 0

    def _ec_add(self, P, Q):
        if P is None: return Q
        if Q is None: return P
        x1, y1 = P
        x2, y2 = Q
        if x1 == x2 and (y1 + y2) % self.p == 0:
            return None
        if x1 == x2 and y1 == y2:
            lam = (3 * x1 * x1 + self._A) * pow(2 * y1, -1, self.p) % self.p
        else:
            lam = (y2 - y1) * pow(x2 - x1, -1, self.p) % self.p
        x3 = (lam * lam - x1 - x2) % self.p
        y3 = (lam * (x1 - x3) - y1) % self.p
        return (x3, y3)

    def _ec_mul(self, k, P):
        R = None
        while k:
            if k & 1:
                R = self._ec_add(R, P)
            P = self._ec_add(P, P)
            k >>= 1
        return R

    def _find_generator(self):
        if self._cached_gen is not None:
            return self._cached_gen, self._cached_order
        for x in range(self.p):
            rhs = (x * x * x + self._A * x + self._B) % self.p
            for y in range(self.p):
                if (y * y) % self.p == rhs:
                    G = (x, y)
                    order = 1
                    cur = G
                    while cur is not None:
                        cur = self._ec_add(cur, G)
                        order += 1
                    if order > 5:
                        self._cached_gen = G
                        self._cached_order = order
                        return G, order
        self._cached_gen = None
        self._cached_order = 0
        return None, 0

    def generate_all(self) -> List[ProblemSpec]:
        G, order = self._find_generator()
        if G is None:
            return []
        specs = []
        for a in range(1, order):
            Q = self._ec_mul(a, G)
            if Q is None:
                continue
            specs.append(ProblemSpec(
                problem_id=self.problem_id,
                prime=self.p,
                inputs=[G[0], G[1], Q[0], Q[1]],
                target=a,
                metadata={"G": G, "Q": Q, "a": a, "order": order},
            ))
        return specs

    def solution_space_size(self) -> int:
        G, order = self._find_generator()
        return max(0, order - 1) if G else 0

    def verify(self, spec: ProblemSpec) -> bool:
        G = spec.metadata["G"]
        a = spec.target
        Q = self._ec_mul(a, G)
        return Q == spec.metadata["Q"]


# ---------------------------------------------------------------------------
# MDLP: Matrix Group Discrete Logarithm — M^a = N in GL(2, F_p)
# ---------------------------------------------------------------------------

class MatrixDLPGenerator(ProblemGenerator):
    """MDLP: Given 2x2 matrices M and N = M^a over F_p, find a.

    Uses F_{p²} arithmetic: a primitive element α = c+di in F_{p²} = F_p[i]
    (where i² = -1) maps to matrix M = [[c, -d], [d, c]] with order p²-1.
    This gives a cyclic subgroup of order p²-1 in GL(2, F_p).
    """
    problem_id = "MDLP"
    n_inputs = 8

    def __init__(self, p: int, seed: int = 42):
        super().__init__(p, seed)
        self._cached_M = None
        self._cached_order = 0

    def _mat_mul(self, A, B):
        a, b, c, d = A
        e, f, g, h = B
        return (
            (a * e + b * g) % self.p,
            (a * f + b * h) % self.p,
            (c * e + d * g) % self.p,
            (c * f + d * h) % self.p,
        )

    def _mat_pow(self, k, M):
        result = (1, 0, 0, 1)
        base = M
        while k:
            if k & 1:
                result = self._mat_mul(result, base)
            base = self._mat_mul(base, base)
            k >>= 1
        return result

    def _fp2_mul(self, x, y):
        """Multiply two elements of F_{p²} represented as (real, imag) with i²=-1."""
        a, b = x
        c, d = y
        return ((a * c - b * d) % self.p, (a * d + b * c) % self.p)

    def _fp2_pow(self, k, x):
        result = (1, 0)
        base = x
        while k:
            if k & 1:
                result = self._fp2_mul(result, base)
            base = self._fp2_mul(base, base)
            k >>= 1
        return result

    def _find_primitive_element_fp2(self):
        """Find a primitive element of F_{p²}* of order p²-1.

        F_{p²} = F_p[i] where i² = -1 (requires p ≡ 3 mod 4 so x²+1 irreducible).
        For p ≡ 1 mod 4, use a different irreducible polynomial.
        """
        if self.p % 4 == 3:
            # x²+1 is irreducible, F_{p²} = F_p[i], i²=-1
            n = self.p * self.p - 1
            factors = set(_prime_factors(n))
            for _ in range(2000):
                c = self.rng.randint(1, self.p - 1)
                d = self.rng.randint(1, self.p - 1)
                alpha = (c, d)
                is_primitive = True
                for q in factors:
                    if self._fp2_pow(n // q, alpha) == (1, 0):
                        is_primitive = False
                        break
                if is_primitive:
                    # Matrix representation: M = [[c, (-d)%p], [d, c]]
                    M = (c, (-d) % self.p, d, c)
                    return M, n
            return None, 0
        else:
            # p ≡ 1 mod 4: find irreducible quadratic x² - t
            for t in range(2, self.p):
                # Check if t is a QR mod p
                if pow(t, (self.p - 1) // 2, self.p) == 1:
                    continue
                # x² - t is irreducible, F_{p²} = F_p[√t]
                n = self.p * self.p - 1
                factors = set(_prime_factors(n))
                for _ in range(2000):
                    c = self.rng.randint(1, self.p - 1)
                    d = self.rng.randint(1, self.p - 1)
                    # (c + d√t)^k in F_{p²}
                    # multiplication: (a+b√t)(c+d√t) = (ac+bdt) + (ad+bc)√t
                    def fp2_mul_t(x, y):
                        a, b = x
                        cc, dd = y
                        return ((a * cc + b * dd * t) % self.p, (a * dd + b * cc) % self.p)
                    def fp2_pow_t(k, x):
                        result = (1, 0)
                        base = x
                        while k:
                            if k & 1:
                                result = fp2_mul_t(result, base)
                            base = fp2_mul_t(base, base)
                            k >>= 1
                        return result
                    alpha = (c, d)
                    is_primitive = True
                    for q in factors:
                        if fp2_pow_t(n // q, alpha) == (1, 0):
                            is_primitive = False
                            break
                    if is_primitive:
                        M = (c, (d * t) % self.p, d, c)
                        return M, n
            return None, 0

    def _find_good_matrix(self):
        if self._cached_M is not None:
            return self._cached_M, self._cached_order
        M, order = self._find_primitive_element_fp2()
        self._cached_M = M
        self._cached_order = order
        return M, order

    def generate(self, n: int) -> List[ProblemSpec]:
        M, order = self._find_good_matrix()
        if M is None or order < 5:
            return []
        if n >= order - 1:
            return self.generate_all()
        specs = []
        seen = set()
        max_attempts = n * 10
        attempts = 0
        while len(specs) < n and attempts < max_attempts:
            a = self.rng.randint(1, order - 1)
            if a not in seen:
                seen.add(a)
                N = self._mat_pow(a, M)
                specs.append(ProblemSpec(
                    problem_id=self.problem_id,
                    prime=self.p,
                    inputs=[M[0], M[1], M[2], M[3], N[0], N[1], N[2], N[3]],
                    target=a,
                    metadata={"M": M, "N": N, "a": a, "order": order},
                ))
            attempts += 1
        return specs

    def generate_all(self) -> List[ProblemSpec]:
        M, order = self._find_good_matrix()
        if M is None or order < 5:
            return []
        specs = []
        for a in range(1, min(order, 500001)):
            N = self._mat_pow(a, M)
            specs.append(ProblemSpec(
                problem_id=self.problem_id,
                prime=self.p,
                inputs=[M[0], M[1], M[2], M[3], N[0], N[1], N[2], N[3]],
                target=a,
                metadata={"M": M, "N": N, "a": a, "order": order},
            ))
        return specs

    def solution_space_size(self) -> int:
        M, order = self._find_good_matrix()
        return max(0, order - 1) if M else 0

    def verify(self, spec: ProblemSpec) -> bool:
        M = spec.metadata["M"]
        a = spec.target
        N = self._mat_pow(a, M)
        return N == spec.metadata["N"]


# ---------------------------------------------------------------------------
# PDLP: Permutation Group Discrete Logarithm — sigma^a = tau in S_n
# ---------------------------------------------------------------------------

class PermutationDLPGenerator(ProblemGenerator):
    """PDLP: Given permutations sigma and tau = sigma^a in S_n, find a.

    sigma is chosen to have large order (a single n-cycle has order n).
    The cyclic group is <sigma> = {sigma^0, sigma^1, ..., sigma^{n-1}}.
    """
    problem_id = "PDLP"
    n_inputs = 0  # variable, set at init

    def __init__(self, p: int, seed: int = 42, n: int = 0):
        super().__init__(p, seed)
        self.n = n if n > 0 else min(p, 127)  # permutation size
        self.n_inputs = self.n * 2  # sigma (n ints) + tau (n ints)
        self._cached_perm = None
        self._cached_order = 0

    def _perm_mul(self, sigma, tau):
        """Compose: (sigma * tau)(i) = sigma[tau[i]]."""
        return [sigma[tau[i]] for i in range(len(sigma))]

    def _perm_pow(self, k, sigma):
        n = len(sigma)
        result = list(range(n))  # identity
        base = list(sigma)
        while k:
            if k & 1:
                result = self._perm_mul(base, result)
            base = self._perm_mul(base, base)
            k >>= 1
        return result

    def _perm_order(self, sigma):
        n = len(sigma)
        result = self._perm_pow(1, sigma)
        order = 1
        identity = list(range(n))
        while result != identity:
            result = self._perm_mul(result, sigma)
            order += 1
            if order > n * n + 1:
                return 0
        return order

    def _find_good_perm(self):
        """Find a permutation with large order (n-cycle has order n)."""
        if self._cached_perm is not None:
            return self._cached_perm, self._cached_order
        n = self.n
        for _ in range(100):
            perm = list(range(n))
            self.rng.shuffle(perm)
            order = self._perm_order(perm)
            if order >= n:
                self._cached_perm = perm
                self._cached_order = order
                return perm, order
        # fallback: a simple n-cycle
        perm = list(range(1, n)) + [0]
        self._cached_perm = perm
        self._cached_order = n
        return perm, n

    def generate_all(self) -> List[ProblemSpec]:
        sigma, order = self._find_good_perm()
        if order < 5:
            return []
        specs = []
        for a in range(1, order):
            tau = self._perm_pow(a, sigma)
            inputs = list(sigma) + list(tau)
            specs.append(ProblemSpec(
                problem_id=self.problem_id,
                prime=self.p,
                inputs=inputs,
                target=a,
                metadata={"sigma": sigma, "tau": tau, "a": a, "order": order, "n": self.n},
            ))
        return specs

    def solution_space_size(self) -> int:
        sigma, order = self._find_good_perm()
        return max(0, order - 1) if sigma else 0

    def verify(self, spec: ProblemSpec) -> bool:
        sigma = spec.metadata["sigma"]
        a = spec.target
        tau = self._perm_pow(a, sigma)
        return tau == spec.metadata["tau"]


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

PROBLEM_REGISTRY: Dict[str, type] = {
    "L6": FiniteFieldDLPGenerator,
    "L7": EllipticCurveDLPGenerator,
    "MDLP": MatrixDLPGenerator,
    "PDLP": PermutationDLPGenerator,
}

N_INPUTS_MAP: Dict[str, int] = {
    "L6": 2,
    "L7": 4,
    "MDLP": 8,
    "PDLP": 0,  # variable, set at init
}


def build_generator(problem: str, p: int, seed: int = 42, **kwargs) -> ProblemGenerator:
    cls = PROBLEM_REGISTRY[problem]
    return cls(p=p, seed=seed, **kwargs)


# ============================================================================
# Tokenizer and Dataset
# ============================================================================

class GrokkingTokenizer:
    """Tokenizes problem specs into integer sequences.

    Vocab layout: [PAD=0, SEP, BOS, EOS, 0, 1, 2, ..., p-1]
    Vocab size = p + 4
    """

    def __init__(self, p: int):
        self.p = p
        self.pad_id = 0
        self.sep_id = 1
        self.bos_id = 2
        self.eos_id = 3
        self.int_offset = 4
        self.vocab_size = p + 4

    def encode(self, spec: ProblemSpec) -> Tuple[List[int], int]:
        tokens = [self.bos_id]
        for i, inp in enumerate(spec.inputs):
            tokens.append(self.int_offset + (inp % self.p))
            if i < len(spec.inputs) - 1:
                tokens.append(self.sep_id)
        tokens.append(self.eos_id)
        target = self.int_offset + (spec.target % self.p)
        return tokens, target

    def decode_token(self, token: int) -> int:
        if token < self.int_offset:
            return -1
        return (token - self.int_offset) % self.p


def compute_max_len(problem: str, p: int, n_inputs: int = 0) -> int:
    n = n_inputs if n_inputs > 0 else N_INPUTS_MAP.get(problem, 2)
    return 2 + n * 2 - 1


class GrokkingDataset(Dataset):
    """PyTorch dataset for grokking experiments."""

    def __init__(self, specs: List[ProblemSpec], tokenizer: GrokkingTokenizer, max_len: int):
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.examples: List[Tuple[torch.Tensor, int]] = []
        for spec in specs:
            tokens, target = tokenizer.encode(spec)
            padded = tokens + [tokenizer.pad_id] * (max_len - len(tokens))
            padded = padded[:max_len]
            self.examples.append((torch.tensor(padded, dtype=torch.long), target))

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        tokens, target = self.examples[idx]
        return tokens, torch.tensor(target, dtype=torch.long)


def split_specs(specs: List[ProblemSpec], n_train: int, seed: int = 42):
    rng = random.Random(seed)
    indices = list(range(len(specs)))
    rng.shuffle(indices)
    train_idx = set(indices[:n_train])
    train = [specs[i] for i in sorted(train_idx)]
    test = [specs[i] for i in indices[n_train:]]
    return train, test


# ============================================================================
# Model — Scaled-up Grokking Transformer (10x)
# ============================================================================

class GrokkingTransformer(nn.Module):
    """Transformer for cyclic DLP grokking.

    Scaled up for LUMI: d_model=512, n_layers=8, n_heads=16 → ~35M params.
    Architecture: token embedding + positional embedding -> N transformer encoder layers
    -> unembedding to vocab logits.
    """

    def __init__(self, vocab_size: int, d_model: int = 512, n_heads: int = 16,
                 n_layers: int = 8, max_len: int = 64, dropout: float = 0.0):
        super().__init__()
        self.vocab_size = vocab_size
        self.d_model = d_model
        self.n_layers = n_layers
        self.max_len = max_len

        self.embed = nn.Embedding(vocab_size, d_model)
        self.pos_embed = nn.Embedding(max_len, d_model)
        self.dropout = nn.Dropout(dropout)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=n_heads,
            dim_feedforward=d_model * 4,
            dropout=dropout,
            batch_first=True,
            activation="gelu",
            norm_first=True,  # pre-norm for better training stability at scale
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.unembed = nn.Linear(d_model, vocab_size)

    def forward(self, tokens: torch.Tensor) -> torch.Tensor:
        B, T = tokens.size()
        pos = torch.arange(T, device=tokens.device).unsqueeze(0).expand(B, T)
        h = self.dropout(self.embed(tokens) + self.pos_embed(pos))
        h = self.transformer(h)
        logits = self.unembed(h)
        return logits

    def count_parameters(self) -> int:
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


def estimate_params(vocab_size: int, d_model: int, n_heads: int, n_layers: int, max_len: int) -> int:
    embed = vocab_size * d_model + max_len * d_model
    per_layer = 12 * d_model * d_model  # attn (4*d^2) + ffn (8*d^2)
    unembed = d_model * vocab_size
    return embed + n_layers * per_layer + unembed


# ============================================================================
# Training Loop with Progressive Weight Decay
# ============================================================================

class PhaseClassifier:
    """Classify training phase based on train/test accuracy."""
    def __init__(self):
        self.history = []

    def classify(self, train_acc: float, test_acc: float, epoch: int) -> str:
        if math.isnan(train_acc):
            return "unknown"
        if train_acc < 0.5:
            return "warmup"
        if test_acc > 0.9:
            return "grokked"
        if train_acc > 0.99 and test_acc < 0.1:
            return "memorization"
        if train_acc > 0.99 and test_acc > 0.1:
            return "transition"
        return "learning"

    def update(self, train_acc: float, test_acc: float, epoch: int) -> str:
        phase = self.classify(train_acc, test_acc, epoch)
        self.history.append((epoch, phase, train_acc, test_acc))
        return phase

    def get_summary(self) -> Dict:
        if not self.history:
            return {}
        grokking_onset = None
        grokking_completion = None
        for epoch, phase, train_acc, test_acc in self.history:
            if phase == "transition" and grokking_onset is None:
                grokking_onset = epoch
            if phase == "grokked" and grokking_completion is None:
                grokking_completion = epoch
        return {
            "grokking_onset": grokking_onset,
            "grokking_completion": grokking_completion,
            "final_phase": self.history[-1][1],
        }


def compute_accuracy(model, dataset, tokenizer, device, batch_size=512):
    """Compute accuracy on a dataset."""
    model.eval()
    correct = 0
    total = 0
    loss_sum = 0.0
    with torch.no_grad():
        for i in range(0, len(dataset), batch_size):
            batch_tokens = []
            batch_targets = []
            for j in range(i, min(i + batch_size, len(dataset))):
                t, tgt = dataset.examples[j]
                batch_tokens.append(t)
                batch_targets.append(tgt)
            tokens = torch.stack(batch_tokens).to(device)
            targets = torch.tensor(batch_targets, dtype=torch.long).to(device)
            logits = model(tokens)
            if logits.dim() == 3:
                seq_lens = (tokens != tokenizer.pad_id).sum(dim=1) - 1
                idx_pos = seq_lens.unsqueeze(-1).unsqueeze(-1).expand(-1, 1, logits.size(-1))
                logits_at_pos = logits.gather(1, idx_pos).squeeze(1)
            else:
                logits_at_pos = logits
            preds = logits_at_pos.argmax(dim=-1)
            correct += (preds == targets).sum().item()
            total += len(targets)
            loss_sum += F.cross_entropy(logits_at_pos, targets).item() * len(targets)
    model.train()
    acc = correct / total if total > 0 else 0.0
    avg_loss = loss_sum / total if total > 0 else 0.0
    return acc, avg_loss


def train_cyclic_dlp(
    problem: str,
    prime: int,
    d_model: int = 512,
    n_layers: int = 8,
    n_heads: int = 16,
    epochs: int = 200_000,
    lr: float = 1e-3,
    wd_start: float = 0.05,
    wd_max: float = 0.30,
    wd_step: float = 0.05,
    wd_acc_threshold: float = 0.05,
    train_size: int = 150_000,
    train_frac: float = 0.3,
    seed: int = 42,
    output_dir: str = "results/lumi",
    checkpoint_interval: int = 1000,
    eval_interval: int = 10,
    early_stop_patience: int = 100,
    early_stop_threshold: float = 0.99,
    use_amp: bool = True,
    log_wandb: bool = False,
    ddp: bool = False,
    perm_n: int = 0,
):
    """Train a cyclic DLP solver with progressive weight decay."""

    # Setup DDP
    local_rank = 0
    world_size = 1
    if ddp:
        local_rank = int(os.environ.get("LOCAL_RANK", 0))
        world_size = int(os.environ.get("WORLD_SIZE", 1))
        torch.distributed.init_process_group(backend="nccl")
        torch.cuda.set_device(local_rank)

    # Device
    if torch.cuda.is_available():
        device = torch.device(f"cuda:{local_rank}" if ddp else "cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")

    if local_rank == 0:
        print(f"Device: {device}", flush=True)

    # Generate dataset
    gen_kwargs = {}
    if problem == "PDLP":
        gen_kwargs["n"] = perm_n if perm_n > 0 else min(prime, 127)

    gen = build_generator(problem, prime, seed=seed, **gen_kwargs)
    tokenizer = GrokkingTokenizer(prime)

    n_actual_inputs = gen.n_inputs if gen.n_inputs > 0 else N_INPUTS_MAP.get(problem, 2)
    max_len = compute_max_len(problem, prime, n_actual_inputs)

    space_size = gen.solution_space_size()
    if local_rank == 0:
        print(f"Problem: {problem}, prime={prime}, space_size={space_size}", flush=True)
        print(f"n_inputs={n_actual_inputs}, max_len={max_len}, vocab_size={tokenizer.vocab_size}", flush=True)

    # Determine train/test sizes
    n_train = min(train_size, space_size - 1) if space_size > 0 else train_size
    n_total = min(n_train * 3 if train_frac == 0.3 else int(n_train / train_frac), space_size) if space_size > 0 else n_train * 3

    if local_rank == 0:
        print(f"Generating dataset: n_train={n_train}, n_total~={n_total}...", flush=True)

    specs = gen.generate(n_total) if n_total < space_size else gen.generate_all()
    train_specs, test_specs = split_specs(specs, n_train, seed=seed)

    train_ds = GrokkingDataset(train_specs, tokenizer, max_len)
    test_ds = GrokkingDataset(test_specs, tokenizer, max_len)

    if local_rank == 0:
        print(f"Train: {len(train_ds)}, Test: {len(test_ds)}", flush=True)

    # Build model
    model = GrokkingTransformer(
        vocab_size=tokenizer.vocab_size,
        d_model=d_model,
        n_heads=n_heads,
        n_layers=n_layers,
        max_len=max_len,
    ).to(device)

    if ddp:
        model = nn.parallel.DistributedDataParallel(
            model, device_ids=[local_rank], output_device=local_rank
        )

    n_params = model.count_parameters() if hasattr(model, 'count_parameters') else sum(p.numel() for p in model.parameters())
    if local_rank == 0:
        print(f"Model: {n_params:,} params, d={d_model}, L={n_layers}, H={n_heads}", flush=True)

    # Optimizer — start with low WD, ramp up
    current_wd = wd_start
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=current_wd)
    last_wd_acc_level = 0

    # AMP scaler
    scaler = torch.amp.GradScaler('cuda') if use_amp and device.type == "cuda" else None
    amp_dtype = torch.float16 if device.type == "cuda" else None

    # Output directory
    if local_rank == 0:
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "checkpoints"), exist_ok=True)

        # Save config
        config = {
            "problem": problem, "prime": prime, "d_model": d_model,
            "n_layers": n_layers, "n_heads": n_heads, "n_params": n_params,
            "epochs": epochs, "lr": lr,
            "wd_schedule": {"start": wd_start, "max": wd_max, "step": wd_step, "acc_threshold": wd_acc_threshold},
            "train_size": len(train_ds), "test_size": len(test_ds),
            "seed": seed, "device": str(device),
            "checkpoint_interval": checkpoint_interval,
            "early_stop_patience": early_stop_patience,
            "early_stop_threshold": early_stop_threshold,
            "use_amp": use_amp, "ddp": ddp, "world_size": world_size,
            "vocab_size": tokenizer.vocab_size, "max_len": max_len,
            "space_size": space_size,
        }
        with open(os.path.join(output_dir, "config.json"), "w") as f:
            json.dump(config, f, indent=2)

    # Prepare tensors (full-batch)
    train_tokens = torch.stack([train_ds.examples[i][0] for i in range(len(train_ds))]).to(device)
    train_targets = torch.tensor([train_ds.examples[i][1] for i in range(len(train_ds))], dtype=torch.long).to(device)

    # Metrics file
    metrics_path = os.path.join(output_dir, "metrics.jsonl") if local_rank == 0 else None
    phase_clf = PhaseClassifier()

    # Training loop
    start_time = time.time()
    consecutive_high = 0
    best_test_acc = 0.0
    early_stopped = False
    full_batch_size = len(train_ds)  # full-batch per GPU

    if local_rank == 0:
        print(f"\nStarting training: {epochs} epochs, batch_size={full_batch_size}", flush=True)
        print(f"WD schedule: start={wd_start}, max={wd_max}, step={wd_step}, threshold={wd_acc_threshold}", flush=True)
        print(f"AMP: {use_amp and device.type == 'cuda'}, DDP: {ddp} (world_size={world_size})", flush=True)
        if ddp:
            print(f"DDP: each GPU processes {full_batch_size // world_size} samples/epoch (strided)", flush=True)
        print("", flush=True)

    for epoch in range(epochs):
        model.train()
        perm = torch.randperm(len(train_ds), device=device)
        epoch_loss = 0.0
        n_batches = 0

        # DDP: strided partition — each GPU processes every world_size-th sample
        if ddp:
            gpu_indices = perm[local_rank::world_size]
        else:
            gpu_indices = perm

        for i in range(0, len(gpu_indices), full_batch_size):
            idx = gpu_indices[i:i + full_batch_size]
            xb = train_tokens[idx]
            yb = train_targets[idx]

            if use_amp and device.type == "cuda":
                with torch.amp.autocast('cuda', dtype=amp_dtype):
                    logits = model(xb)
                    if logits.dim() == 3:
                        seq_lens = (xb != tokenizer.pad_id).sum(dim=1) - 1
                        idx_pos = seq_lens.unsqueeze(-1).unsqueeze(-1).expand(-1, 1, logits.size(-1))
                        logits_at_pos = logits.gather(1, idx_pos).squeeze(1)
                    else:
                        logits_at_pos = logits
                    loss = F.cross_entropy(logits_at_pos, yb)

                optimizer.zero_grad()
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                logits = model(xb)
                if logits.dim() == 3:
                    seq_lens = (xb != tokenizer.pad_id).sum(dim=1) - 1
                    idx_pos = seq_lens.unsqueeze(-1).unsqueeze(-1).expand(-1, 1, logits.size(-1))
                    logits_at_pos = logits.gather(1, idx_pos).squeeze(1)
                else:
                    logits_at_pos = logits
                loss = F.cross_entropy(logits_at_pos, yb)

                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

        avg_train_loss = epoch_loss / n_batches

        # Evaluate (only on rank 0 when DDP to avoid redundant eval)
        if epoch % eval_interval == 0 or epoch == epochs - 1:
            if ddp and local_rank != 0:
                train_acc = float("nan")
                test_acc = float("nan")
                test_loss = avg_train_loss
            else:
                train_acc, _ = compute_accuracy(model, train_ds, tokenizer, device, batch_size=512)
                test_acc, test_loss = compute_accuracy(model, test_ds, tokenizer, device, batch_size=512)

            # Progressive weight decay ramp
            if not math.isnan(train_acc):
                acc_level = int(train_acc / wd_acc_threshold)
                if acc_level > last_wd_acc_level and current_wd < wd_max:
                    new_wd = min(current_wd + wd_step, wd_max)
                    for pg in optimizer.param_groups:
                        pg['weight_decay'] = new_wd
                    if local_rank == 0:
                        print(f"  WD ramp: {current_wd:.3f} -> {new_wd:.3f} (train_acc={train_acc:.4f}, level={acc_level})", flush=True)
                    current_wd = new_wd
                    last_wd_acc_level = acc_level
        else:
            train_acc = float("nan")
            test_acc = float("nan")
            test_loss = avg_train_loss

        # DDP barrier: ensure all GPUs sync after eval (rank 0 may have taken longer)
        if ddp and (epoch % eval_interval == 0 or epoch == epochs - 1):
            torch.distributed.barrier()

        # Track best
        if not math.isnan(test_acc):
            if test_acc > best_test_acc:
                best_test_acc = test_acc

        # Phase classification
        phase = phase_clf.update(train_acc if not math.isnan(train_acc) else 0.0,
                                 test_acc if not math.isnan(test_acc) else 0.0, epoch)
        is_transition = (phase == "grokked" and
                         len(phase_clf.history) >= 2 and
                         phase_clf.history[-2][1] != "grokked")

        # Log metrics
        if local_rank == 0 and metrics_path:
            elapsed = time.time() - start_time
            metrics = {
                "epoch": epoch,
                "train_acc": train_acc if not math.isnan(train_acc) else None,
                "test_acc": test_acc if not math.isnan(test_acc) else None,
                "train_loss": avg_train_loss,
                "test_loss": test_loss if not math.isnan(test_loss) else None,
                "weight_decay": current_wd,
                "phase": phase,
                "elapsed_s": elapsed,
                "best_test_acc": best_test_acc,
            }
            with open(metrics_path, "a") as f:
                f.write(json.dumps(metrics) + "\n")

        # Checkpoint
        if local_rank == 0 and (epoch + 1) % checkpoint_interval == 0:
            ckpt_path = os.path.join(output_dir, "checkpoints", f"epoch_{epoch:06d}.pt")
            torch.save({
                "epoch": epoch,
                "model_state_dict": (model.module if ddp else model).state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "current_wd": current_wd,
                "best_test_acc": best_test_acc,
            }, ckpt_path)

        # Progress log
        if local_rank == 0 and (epoch % 100 == 0 or epoch == epochs - 1 or (test_acc > 0.1 and epoch % eval_interval == 0)):
            elapsed = time.time() - start_time
            print(f"  Epoch {epoch}/{epochs} | train={train_acc:.4f} test={test_acc:.4f} "
                  f"loss={avg_train_loss:.4f} wd={current_wd:.3f} phase={phase} t={elapsed:.1f}s", flush=True)

        # Early stopping
        if not math.isnan(test_acc) and test_acc > early_stop_threshold:
            consecutive_high += 1
            if consecutive_high >= early_stop_patience:
                if local_rank == 0:
                    print(f"\nEarly stopped at epoch {epoch} (test_acc > {early_stop_threshold} for {consecutive_high} evals)", flush=True)
                early_stopped = True
        else:
            consecutive_high = 0

        if early_stopped:
            break

    # Final checkpoint
    if local_rank == 0:
        final_path = os.path.join(output_dir, "checkpoints", "final.pt")
        torch.save({
            "epoch": epoch,
            "model_state_dict": (model.module if ddp else model).state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "current_wd": current_wd,
            "best_test_acc": best_test_acc,
        }, final_path)

        # Summary
        summary = phase_clf.get_summary()
        summary["best_test_acc"] = best_test_acc
        summary["total_epochs"] = epoch + 1
        summary["final_wd"] = current_wd
        summary["n_params"] = n_params
        with open(os.path.join(output_dir, "summary.json"), "w") as f:
            json.dump(summary, f, indent=2)

        elapsed = time.time() - start_time
        print(f"\nTraining complete: {epoch + 1} epochs in {elapsed:.1f}s", flush=True)
        print(f"Best test acc: {best_test_acc:.4f}", flush=True)
        print(f"Final WD: {current_wd:.3f}", flush=True)
        print(f"Summary: {json.dumps(summary, indent=2)}", flush=True)

    if ddp:
        torch.distributed.destroy_process_group()


# ============================================================================
# Dataset Generation (standalone)
# ============================================================================

def generate_dataset(
    problem: str,
    prime: int,
    train_size: int,
    output_dir: str,
    seed: int = 42,
    perm_n: int = 0,
):
    """Generate and save a dataset to disk for later training."""
    gen_kwargs = {}
    if problem == "PDLP":
        gen_kwargs["n"] = perm_n if perm_n > 0 else min(prime, 127)

    gen = build_generator(problem, prime, seed=seed, **gen_kwargs)
    tokenizer = GrokkingTokenizer(prime)
    n_actual_inputs = gen.n_inputs if gen.n_inputs > 0 else N_INPUTS_MAP.get(problem, 2)
    max_len = compute_max_len(problem, prime, n_actual_inputs)

    space_size = gen.solution_space_size()
    n_train = min(train_size, space_size - 1) if space_size > 0 else train_size
    n_total = min(n_train * 3, space_size) if space_size > 0 else n_train * 3

    print(f"Generating dataset: {problem}, p={prime}", flush=True)
    print(f"  space_size={space_size}, n_train={n_train}, n_total~={n_total}", flush=True)

    specs = gen.generate(n_total) if n_total < space_size else gen.generate_all()
    train_specs, test_specs = split_specs(specs, n_train, seed=seed)

    train_ds = GrokkingDataset(train_specs, tokenizer, max_len)
    test_ds = GrokkingDataset(test_specs, tokenizer, max_len)

    os.makedirs(output_dir, exist_ok=True)
    dataset_path = os.path.join(output_dir, f"{problem}_p{prime}_train{n_train}.pt")
    torch.save({
        "train": [(t, tgt) for t, tgt in train_ds.examples],
        "test": [(t, tgt) for t, tgt in test_ds.examples],
        "metadata": {
            "problem": problem,
            "prime": prime,
            "space_size": space_size,
            "n_train": len(train_specs),
            "n_test": len(test_specs),
            "max_len": max_len,
            "vocab_size": tokenizer.vocab_size,
            "seed": seed,
        },
    }, dataset_path)

    print(f"Saved dataset: {dataset_path}", flush=True)
    print(f"  Train: {len(train_ds)}, Test: {len(test_ds)}, Vocab: {tokenizer.vocab_size}, Max len: {max_len}", flush=True)
    return dataset_path


# ============================================================================
# CLI
# ============================================================================

def main():
    ap = argparse.ArgumentParser(description="LUMI Cyclic DLP Trainer — 10x scale, all DLP types")
    ap.add_argument("--problem", type=str, default="L6",
                    choices=list(PROBLEM_REGISTRY.keys()),
                    help="DLP problem type: L6=finite field, L7=elliptic curve, MDLP=matrix group, PDLP=permutation")
    ap.add_argument("--prime", type=int, default=10007,
                    help="Prime modulus (10x local: 10007 = 14-bit vs 1013 = 10-bit)")
    ap.add_argument("--d-model", type=int, default=512,
                    help="Model dimension (10x local: 512 vs 256)")
    ap.add_argument("--n-layers", type=int, default=8,
                    help="Transformer layers (2x local: 8 vs 4)")
    ap.add_argument("--n-heads", type=int, default=16,
                    help="Attention heads (2x local: 16 vs 8)")
    ap.add_argument("--epochs", type=int, default=200_000)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--wd-start", type=float, default=0.05,
                    help="Starting weight decay for progressive schedule")
    ap.add_argument("--wd-max", type=float, default=0.30,
                    help="Maximum weight decay to ramp up to")
    ap.add_argument("--wd-step", type=float, default=0.05,
                    help="WD increment per train acc threshold crossing")
    ap.add_argument("--wd-acc-threshold", type=float, default=0.05,
                    help="Train acc improvement step to trigger WD increase (0.05 = every 5%%)")
    ap.add_argument("--train-size", type=int, default=150_000,
                    help="Training set size (20x local: 150k vs 7.5k)")
    ap.add_argument("--train-frac", type=float, default=0.3,
                    help="Fraction of total that is training (30%% train, 70%% test)")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--output-dir", type=str, default="results/lumi")
    ap.add_argument("--checkpoint-interval", type=int, default=1000)
    ap.add_argument("--eval-interval", type=int, default=10)
    ap.add_argument("--early-stop-patience", type=int, default=100)
    ap.add_argument("--early-stop-threshold", type=float, default=0.99)
    ap.add_argument("--no-amp", action="store_true", help="Disable mixed precision")
    ap.add_argument("--ddp", action="store_true", help="Use DistributedDataParallel (for multi-GPU)")
    ap.add_argument("--perm-n", type=int, default=0,
                    help="Permutation size for PDLP (default: min(prime, 127))")
    ap.add_argument("--generate-only", action="store_true",
                    help="Only generate dataset, don't train")
    args = ap.parse_args()

    if args.generate_only:
        generate_dataset(
            problem=args.problem,
            prime=args.prime,
            train_size=args.train_size,
            output_dir=args.output_dir,
            seed=args.seed,
            perm_n=args.perm_n,
        )
        return

    train_cyclic_dlp(
        problem=args.problem,
        prime=args.prime,
        d_model=args.d_model,
        n_layers=args.n_layers,
        n_heads=args.n_heads,
        epochs=args.epochs,
        lr=args.lr,
        wd_start=args.wd_start,
        wd_max=args.wd_max,
        wd_step=args.wd_step,
        wd_acc_threshold=args.wd_acc_threshold,
        train_size=args.train_size,
        train_frac=args.train_frac,
        seed=args.seed,
        output_dir=args.output_dir,
        checkpoint_interval=args.checkpoint_interval,
        eval_interval=args.eval_interval,
        early_stop_patience=args.early_stop_patience,
        early_stop_threshold=args.early_stop_threshold,
        use_amp=not args.no_amp,
        ddp=args.ddp,
        perm_n=args.perm_n,
    )


if __name__ == "__main__":
    main()
